# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8dc16730-63dd-4b65-be01-06e03ce89311";
      fsType = "ext4";
    };

  fileSystems."/nix/store" =
    { device = "/nix/store";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9FA1-35B9";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/var/lib/docker/rootfs/overlayfs/b3d7cd571fe646a9c7f20c8cc22f38983cf70aadec3b6531b535f767fb02dbcf" =
    { device = "overlay";
      fsType = "overlay";
    };

  fileSystems."/var/lib/docker/rootfs/overlayfs/5e7332fdcc34ebc796f025f422ef32a1373961d544cf3c5cc46989b6b5b6ae3c" =
    { device = "overlay";
      fsType = "overlay";
    };

  fileSystems."/var/lib/docker/rootfs/overlayfs/f71287c56e03e0cd25a59311d3f87de8fa6182edcaf8d083e5001e3decd02690" =
    { device = "overlay";
      fsType = "overlay";
    };

  fileSystems."/var/lib/docker/rootfs/overlayfs/05d089b0d0546181c92c9a950366a0cd94aabaea76428aab09fcc98aa4162aec" =
    { device = "overlay";
      fsType = "overlay";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/888ad3e3-40f4-476c-8991-aaec95b1e08d"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
